### ISSUE TITLE
AttributeError: module 'tf_utils.common' has no attribute 'leaky_relu'

### ISSUE THREAD

**Issue by xtarx** [cih9088/Tensorflow_practice#2]
`activation_fn=common.leaky_relu):` 

the function "leaky_relu" is not implemented in the common.py file

**Comment by cih9088** [comment]
The function is appended.

**Comment by xtarx** [comment]
Thank you for your swift response,  I believe you have a small typo in the common.py file its 

`    return tf.maximun(x, leak * x)  ===> return tf.maximum(x, leak * x)`

**Comment by cih9088** [comment]
Thanks for your concern. That would be corrected asap :)

**Comment by xtarx** [comment]
One other request, have you tried training MNIST on ALI ? 

It seems that the discriminator tends to overtake the generator early one, it's converging way faster than the generator

```
Counter: 14	 D_loss: 0.2710	 G_loss: 10.5475
Counter: 15	 D_loss: 0.2317	 G_loss: 11.2325
Counter: 16	 D_loss: 0.2862	 G_loss: 10.9400
Counter: 17	 D_loss: 0.2261	 G_loss: 11.5977
Counter: 18	 D_loss: 0.2998	 G_loss: 11.1243
Counter: 19	 D_loss: 0.2218	 G_loss: 11.5344
Counter: 20	 D_loss: 0.2033	 G_loss: 11.9585
Counter: 21	 D_loss: 0.2669	 G_loss: 11.7361
Counter: 22	 D_loss: 0.2506	 G_loss: 11.4886
Counter: 23	 D_loss: 0.2192	 G_loss: 11.8008
Counter: 24	 D_loss: 0.2459	 G_loss: 11.7715
Counter: 25	 D_loss: 0.2243	 G_loss: 11.8992
Counter: 26	 D_loss: 0.2410	 G_loss: 11.8430
Counter: 27	 D_loss: 0.2479	 G_loss: 11.7513
Counter: 28	 D_loss: 0.2604	 G_loss: 11.5026
```
